### ISSUE TITLE
Improve results in departmental search

### ISSUE THREAD

**Issue by nathanhleung** [nathanhleung/grades.natecation.xyz#10]
chem dept should be higher here

<img width="734" alt="Screenshot 2023-07-15 at 13 51 29" src="https://github.com/nathanhleung/grades.natecation.xyz/assets/10874225/25f1cb64-5af3-46af-858a-a3e0da6bd9b1">

**Comment by TomBinford** [comment]
Same for "engr"
![image](https://github.com/nathanhleung/grades.natecation.xyz/assets/28466971/dcc6ebe5-dd17-4bab-93ef-d89ea666b3b9)
