### ISSUE TITLE
Add the ability to search by professor

### ISSUE THREAD

**Issue by ryland-goldman** [nathanhleung/grades.natecation.xyz#16]
Sometimes, I have a professor who hasn't taught a particular class before (or at least recently). When I want a sense of the professor's grading style, it would be great if I had the ability to pull up other classes they recently taught.

This feature — searching by professor — is provided by Bruinwalk, and would be a good addition to this site too.

For example, I'm taking Physics 115A this fall with Dr. Gutperle. He does not appear under "Physics 115A" because he hasn't taught it in a long time, but I still want to estimate whether or not I will be able to get an A. So I have to **manually** look through every physics class to find that he also taught Physics 105A back in 2022, and I'm able to view the distribution there. Whereas on Bruinwalk, I'm able to just search his name and pull up his reviews across all classes.

**Comment by nathanhleung** [comment]
Hi @ryland-goldman, thanks for the feature request — just implemented it. Let me know if you have any feedback!

https://grades.natecation.xyz/?instructor=GUTPERLE%2C+MICHAEL

https://github.com/user-attachments/assets/133f55a4-3396-4667-b69a-f2ecca03cd3b
